---
- hosts: 172.31.18.165
  become: yes
  tasks:
  - name: i want to execute dirt linux command
    command: apt-get install apache2 -y
    register: myresult
  - name: disply myresult
    debug:
      msg: "{{myresult}}"
  - name: install tree
    apt:
      name: tree
      state: present
    when: myresult.stderr==""
    
  - name: install wget
    apt:
      name: wget
      state: present
    when: myresult.stderr!=""
    