---
- hosts: 172.31.18.165
  become: yes
  tasks:
  - name: i want to execute dirt linux command
    command: hostname -f
    register: myresult
  - name: disply myresult
    debug:
      msg: "{{myresult}}"