---
- hosts: 172.31.18.165
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install webserver
    apt:
     name: apache2
     state: present

  - name: restart webserver
    service:
      name: apache2
      state: restarted
  - name: copy myindexfile into ansible nodes side
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
