---
- hosts: 172.31.18.165
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install webserver
    apt:
     name: apache2
     state: present

  - name: start webserver
    service:
      name: apache2
      state: restarted

