---
- name: copy tomcat user file into nodes side
  template:
     src: templates/mytomuser.j2
     dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy manager context file into node side
  template:
    src:  templates/mymanager.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy host manager context file into node side
  template:
     src: templates/myhostmanager.j2
     dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml